"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-04-10 18:30:02.364469

"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.Enum('SBI', 'HDFC', name='bank'), nullable=False),
    sa.Column('account_number_masked', sa.String(length=8), nullable=False),
    sa.Column('holder_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)

    op.create_table('category_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_kind', sa.String(length=32), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('dependents', sa.Integer(), nullable=False),
    sa.Column('annual_income_paise', sa.Integer(), nullable=False),
    sa.Column('one_off_threshold_paise', sa.Integer(), nullable=False),
    sa.Column('leak_merchant_count_threshold', sa.Integer(), nullable=False),
    sa.Column('leak_merchant_amount_threshold_paise', sa.Integer(), nullable=False),
    sa.Column('anomaly_multiplier', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_canonical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_description_pattern', sa.Text(), nullable=False),
    sa.Column('canonical_name', sa.String(length=128), nullable=False),
    sa.Column('category_hint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('bank', sa.Enum('SBI', 'HDFC', name='bank'), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CLASSIFYING', 'EXTRACTING', 'RECONCILING', 'READY_FOR_REVIEW', 'APPROVED', 'REJECTED', 'FAILED', name='documentstatus'), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('txn_count_extracted', sa.Integer(), nullable=False),
    sa.Column('txn_count_new', sa.Integer(), nullable=False),
    sa.Column('txn_count_duplicate', sa.Integer(), nullable=False),
    sa.Column('classified_at', sa.DateTime(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_sha256')
    )
    op.create_table('recurring_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('merchant_canonical', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('cadence', sa.String(length=16), nullable=False),
    sa.Column('typical_amount_paise', sa.Integer(), nullable=False),
    sa.Column('typical_day_of_month', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('description_normalized', sa.Text(), nullable=False),
    sa.Column('merchant_canonical', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('category_source', sa.String(length=16), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_essential', sa.Boolean(), nullable=False),
    sa.Column('balance_after_paise', sa.Integer(), nullable=True),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('within_day_counter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key', name='uq_transactions_dedup_key')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_category'))

    op.drop_table('transactions')
    op.drop_table('recurring_series')
    op.drop_table('documents')
    op.drop_table('merchant_canonical')
    op.drop_table('config')
    op.drop_table('category_overrides')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))

    op.drop_table('audit_log')
    op.drop_table('accounts')
    # ### end Alembic commands ###
